# config/nodes.yaml

masters:
  - name: master-1
    ip: 192.168.1.15
    bootstrap: true
  - name: master-2
    ip: 192.168.1.16
  - name: master-3
    ip: 192.168.1.17
workers:
  - name: worker-1
    ip: 192.168.1.18
  - name: worker-2
    ip: 192.168.1.19
  # - name: worker-3
  #   ip: 192.168.1.20
  # - name: worker-4
  #   ip: 192.168.1.21
